#!/bin/sh

/usr/bin/invoke_app "$@" -t jupyterguide70 \
                         -C "start_jupyter --themes -T @tool Index.ipynb" \
                         -u anaconda-7 \
                         -w headless \
                         -r none